output_dir: ./output/cifar10/resnet/shard/client50/test
datapath: ./data/generated_dataset/cifar10/shard_50
seed: 111
save_interval: 1
model:
  model_name: ResNet
  block: BasicBlock
  num_classes: 10
  num_blocks: [2,2,2,2]  
server:
  base: avg
  num_clients: 50
  num_join_clients: 10
  epochs: 300
  batch_size: 1024
  aggregate_cov: False
  svd_proj: False
client:
  base: mrl
  prefix: True
  topk: 100
  alpha: 0.5
  batch_size : 64
  local_epochs: 10
  loss:
    loss_name: CrossEntropyLoss
    label_smoothing: 0
  save_client: True
  optimizer:
    optimizer_name: SGD
    lr: 0.01
    weight_decay: 0.0005
    momentum: 0.9
  transform:
    use_transform: False
